### ISSUE TITLE
启动时的报错

### ISSUE THREAD

**Issue by a1232580** [kitUIN/nonebot-plugin-ncm#15]
07-24 03:30:58 [INFO] nonebot-plugin-ncm | 检测到缓存，自动加载用户
07-24 03:30:58 [SUCCESS] nonebot-plugin-ncm | 欢迎您网易云用户:以湿 [483220795]
07-24 03:30:58 [ERROR] nonebot | Failed to import "nonebot-plugin-ncm"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\df\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\df\Desktop\df\.venv\Lib\site-packages\nonebot-plugin-ncm\__init__.py", line 23, in <module>
    @dataclass(eq=False)
  File "C:\Users\df\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "C:\Users\df\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
  File "C:\Users\df\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'nonebot-plugin-ncm.config.Config'> for field config is not allowed: use default_factory
07-24 03:30:59 [SUCCESS] nonebot | Succeeded to load plugin
更新后启动就报错了

**Comment by kitUIN** [comment]
请使用1.6.1
