### ISSUE TITLE
没想到是老插件背刺我的菜单wwww

### ISSUE THREAD

**Issue by a1232580** [kitUIN/nonebot-plugin-ncm#17]
```
07-26 02:36:28 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\internal\driver\driver.py", line 150, in _run_hook
    await asyncio.gather(*coros)
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\utils.py", line 186, in run_coro_with_catch
    return await coro
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_PicMenu\__init__.py", line 21, in _
    menu_manager.load_plugin_info()
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 170, in load_plugin_info
    self.data_manager.load_plugin_info()
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 80, in load_plugin_info
    load_from_dict(meta_data)
  File "C:\Users\User\Desktop\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 49, in load_from_dict
    funcs=_meta_data.extra['menu_data'] if 'menu_data' in _meta_data.extra else None,
AttributeError: 'PluginMetadata' object has no attribute 'extra'```

**Comment by kitUIN** [comment]
请使用1.6.2
