### ISSUE TITLE
下载指令报错，求教

### ISSUE THREAD

**Issue by salspica** [kitUIN/nonebot-plugin-ncm#21]
版本v1.6.5

**日志**

08-24 06:06:58 [INFO] nonebot-plugin-ncm | 已识别NID:2068401809的歌曲
08-24 06:06:58 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-ncm) running complete
08-24 06:07:10 [SUCCESS] nonebot | OneBot V11 3187539714 | [message.group.normal]: Message -1584268003 from 2648571809@[
群:298448179] '[reply:id=-694760053][at:qq=2648571809] 下载'
08-24 06:07:10 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-ncm)
08-24 06:07:12 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-ncm) running complete
08-24 06:07:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-ncm) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\NBbBOT\bot.py", line 15, in <module>
    nonebot.run()
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_
run
    await handler(
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\NBbBOT\.venv\Lib\site-packages\nonebot-plugin-ncm\__init__.py", line 167, in music_reply_
receive
    await nncm.upload_group_data_file(event.group_id, data, bot_id=info["bot_id"])
TypeError: Ncm.upload_group_data_file() got an unexpected keyword argument 'bot_id'
08-24 06:07:46 [SUCCESS] nonebot | OneBot V11 3187539714 | [notice.group_recall]: {'time': 1692828430, 'self_id': 318753
9714, 'post_type': 'notice', 'notice_type': 'group_recall', 'user_id': 2648571809, 'group_id': 298448179, 'operator_id':
 2648571809, 'message_id': -1584268003}

**Comment by kitUIN** [comment]
可能是新版本使用了旧版本的缓存文件导致，尝试将db文件夹内的ncm开头文件删除试试？

**Comment by kitUIN** [comment]
代码问题，过会修

**Comment by salspica** [comment]
> 可能是新版本使用了旧版本的缓存文件导致，尝试将db文件夹内的ncm开头文件删除试试？

清除缓存文件后下载指令依然相同报错

**Comment by salspica** [comment]
> 代码问题，过会修

感谢

**Comment by kitUIN** [comment]
已经修复,请使用`1.6.6`版本
