### ISSUE TITLE
ncm插件突然无法使用

### ISSUE THREAD

**Issue by MomentQYC** [kitUIN/nonebot-plugin-ncm#22]
报错信息（所有QQ号以{QQ}替代）
使用最新的ncm插件
```
[ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-ncm) failed.
Traceback (most recent call last):

  File "<string>", line 17, in <module>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f596ffe92d0>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 199, in run
    uvicorn.run(
    │       └ <function run at 0x7f596f973640>
    └ <module 'uvicorn' from '/usr/local/lib/python3.10/dist-packages/uvicorn/__init__.py'>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x7f596f973a30>
    └ <uvicorn.server.Server object at 0x7f593e800700>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f596f973ac0>
           │       │   └ <uvicorn.server.Server object at 0x7f593e800700>
           │       └ <function run at 0x7f5971156320>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f593e81d000>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
          └ <function _run_matcher at 0x7f596fd48f70>
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function matcher_mutex at 0x7f596e5cc3a0>: <Task finished name='Task-255439' coro=<AsyncExitStack.enter_async_context() don...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f595e88d2a0>
          │       │   │    │      └ {'_prefix': {'command': ('点歌',), 'raw_command': '点歌', 'command_arg': [MessageSegment(type='text', data={'text': '喵喵喵喵喵喵喵喵喵喵喵喵...
          │       │   │    └ GroupMessageEvent(time=1698560403, self_id={QQ}, post_type='message', sub_type='normal', user_id={QQ}, message_ty...
          │       │   └ Bot(type='OneBot V11', self_id='{QQ}')
          │       └ <function Matcher.run at 0x7f596fe1cf70>
          └ Matcher(type='message', module=nonebot-plugin-ncm)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function matcher_mutex at 0x7f596e5cc3a0>: <Task finished name='Task-255439' coro=<AsyncExitStack.enter_async_context() don...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f595e88d2a0>
          │    │          │    │      └ {'_prefix': {'command': ('点歌',), 'raw_command': '点歌', 'command_arg': [MessageSegment(type='text', data={'text': '喵喵喵喵喵喵喵喵喵喵喵喵...
          │    │          │    └ GroupMessageEvent(time=1698560403, self_id={QQ}, post_type='message', sub_type='normal', user_id={QQ}, message_ty...
          │    │          └ Bot(type='OneBot V11', self_id='{QQ}')
          │    └ <function Matcher.simple_run at 0x7f596fe1cee0>
          └ Matcher(type='message', module=nonebot-plugin-ncm)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
    await handler(
          └ Dependent(call=receive_song, parameterless=(Depends(Dependent(call=_key_getter)),))
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='{QQ}'), 'event': GroupMessageEvent(time=1698560403, self_id={QQ}, post_ty...
                 │    │             │         │    │    └ <function receive_song at 0x7f593e9bf9a0>
                 │    │             │         │    └ Dependent(call=receive_song, parameterless=(Depends(Dependent(call=_key_getter)),))
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7f59711e5f30>
  File "/usr/local/lib/python3.10/dist-packages/nonebot-plugin-ncm/__init__.py", line 128, in receive_song
    _id = await nncm.search_song(keyword=str(song), limit=1)
                │    │                       └ [MessageSegment(type='text', data={'text': '喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵'})]
                │    └ <function Ncm.search_song at 0x7f593e9bdfc0>
                └ <nonebot-plugin-ncm.data_source.Ncm object at 0x7f593e9b6500>
  File "/usr/local/lib/python3.10/dist-packages/nonebot-plugin-ncm/data_source.py", line 149, in search_song
    data = res["songs"]
           └ {'code': 50000005}

KeyError: 'songs'
```

**Comment by kitUIN** [comment]
看起来像是偶尔的请求返回失败
经常触发么?

**Comment by MomentQYC** [comment]
> 看起来像是偶尔的请求返回失败
> 经常触发么?

目前是稳定触发，重启机器人无效

**Comment by kitUIN** [comment]
考虑是其他原因,我这边没法重现这个bug

**Comment by YXdevve** [comment]
我这里也稳定触发这个bug 重启，重装均不能解决
KeyError: 'songs'

**Comment by kitUIN** [comment]
尝试修复,各位请使用1.6.8版本尝试

**Comment by YXdevve** [comment]
更换1.6.8后依然出现此问题 报错信息相同

**Comment by kitUIN** [comment]
尝试删除ncm_cache.json之后重新登录?

**Comment by YXdevve** [comment]
删除ncm_cache.json之后重新登录可以恢复正常使用了 谢谢
