### ISSUE TITLE
有报错，但还是发出歌曲卡片了

### ISSUE THREAD

**Issue by RainbowDashKira** [kitUIN/nonebot-plugin-ncm#23]
版本是仓库clone的
10-30 15:49:29 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-ncm) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot-plugin-ncm\__init__.py", line 130, in receive_song
    nncm.get_song(message_id=message_id["message_id"], nid=_id)
TypeError: Ncm.get_song() missing 1 required positional argument: 'bot_id'

**Comment by kitUIN** [comment]
已修复,请使用1.6.7
