### ISSUE TITLE
下载提示文件不存在

### ISSUE THREAD

**Issue by WindStill** [kitUIN/nonebot-plugin-ncm#24]
是因为nonebot和QQ客户端不在同一台机器上吗？

![image](https://github.com/kitUIN/nonebot-plugin-ncm/assets/958456/e6450f12-1a55-4a9b-9f19-67cb6f743c70)

```
12-01 07:00:39 [SUCCESS] nonebot | OneBot V11 {QQ} | [message.group.normal]: Message 424689002 from 270868687@[群:480972491] 'https://music.163.com/#/song?id=5201824'
12-01 07:00:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-ncm, lineno=101)
12-01 07:00:39 [INFO] nonebot-plugin-ncm | 已识别NID:5201824的歌曲
12-01 07:00:39 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-ncm, lineno=101) running complete
12-01 07:00:51 [SUCCESS] nonebot | OneBot V11 {QQ} | [message.group.normal]: Message 170271325 from 270868687@[群:480972491] '[reply:id=424689002]下载'
12-01 07:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-ncm, lineno=107)
12-01 07:00:51 [ERROR] nonebot-plugin-ncm | ActionFailed(status='failed', retcode=10003, data={}, message='文件不存在', echo='8')
12-01 07:00:51 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-ncm, lineno=107) running complete
12-01 07:00:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-ncm, lineno=107) failed.
Traceback (most recent call last):
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot-plugin-ncm/data_source.py", line 214, in upload_group_file
    await bot.upload_group_file(group_id=group_id, file=file, name=name)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 123, in call_api
    raise exception
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 144, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=10003, data={}, message='文件不存在', echo='8')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/root/qqbot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/qqbot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot-plugin-ncm/__init__.py", line 167, in music_reply_receive
    await nncm.upload_group_data_file(event.group_id, data, bot_id=info["bot_id"])
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot-plugin-ncm/data_source.py", line 205, in upload_group_data_file
    await self.upload_group_file(group_id=group_id, file=data["file"], name=data["filename"], bot_id=bot_id)
  File "/root/qqbot/.venv/lib/python3.11/site-packages/nonebot-plugin-ncm/data_source.py", line 218, in upload_group_file
    if isinstance(e, ActionFailed) and e.info["wording"] == "server" \
KeyError: 'wording'
```

**Comment by lgc2333** [comment]
是的

**Comment by kitUIN** [comment]
请尝试1.6.9

**Comment by WindStill** [comment]
> 请尝试1.6.9

请问怎么查看插件版本？我是用 nb cli 安装的，也用了更新指令更新到了最新版本。
