### ISSUE TITLE
启动时，登录报错

### ISSUE THREAD

**Issue by Cherryluoying** [kitUIN/nonebot-plugin-ncm#27]
系统:Windows server 2019
Python版本:3.9.10
nonebot2版本:2.3.1

06-16 18:08:32 [SUCCESS] nonebot | NoneBot is initializing...
06-16 18:08:32 [INFO] nonebot | Current Env: prod
06-16 18:08:33 [WARNING] nonebot-plugin-ncm | 您未填写账号,自动进入二维码登录模式
06-16 18:08:33 [INFO] nonebot-plugin-ncm | 二维码已经保存在当前目录下的ncm.png，请使用手机网易云客户端扫码登录。
06-16 18:08:54 [ERROR] nonebot | Failed to import "nonebot-plugin-ncm"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot-plugin-ncm\__init__.py", line 17, in <module>
    from .data_source import nncm, ncm_config, setting, Q, cmd
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot-plugin-ncm\data_source.py", line 317, in <module>
    nncm.get_qrcode()
  File "C:\Users\Administrator\llonebotnb\.venv\lib\site-packages\nonebot-plugin-ncm\data_source.py", line 118, in get_qrcode
    self.api.login.WriteLoginInfo(st)
TypeError: WriteLoginInfo() missing 1 required positional argument: 'session'

**Comment by kitUIN** [comment]
可能是你装的pyncm版本过高了？
看看是什么版本

**Comment by Windsland52** [comment]
> 可能是你装的pyncm版本过高了？ 看看是什么版本

同报错。直接通过nb安的，pyncm好像是1.6.15，应该比1.6.9.1高。为啥通过nb安就没按pyproject.toml
来呢

**Comment by Windsland52** [comment]
> > 可能是你装的pyncm版本过高了？ 看看是什么版本
> 
> 同报错。直接通过nb安的，pyncm好像是1.6.15，应该比1.6.9.1高。为啥通过nb安就没按pyproject.toml 来呢

刚试了下，pyncm重安1.6.9.1就好了

**Comment by PaperPig** [comment]
同报错 pyncm重装1.6.9.1也不能启动

**Comment by kitUIN** [comment]
请使用最新版
