### ISSUE TITLE
所有消息都会返回这个，但好像不影响使用

### ISSUE THREAD

**Issue by RainbowDashKira** [kitUIN/nonebot-plugin-ncm#31]
Rule check failed for Matcher(type='message', module=nonebot-plugin-ncm, lineno=103).
  + Exception Group Traceback (most recent call last):
  |   File "<string>", line 15, in <module>
  |     nonebot.run()
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
  |     get_driver().run(*args, **kwargs)
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
  |     uvicorn.run(
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
  |     server.run()
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
  |     return asyncio.run(self.serve(sockets=sockets))
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
  |     return runner.run(main)
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
  |     self.run_forever()
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
  |     self._run_once()
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
  |     handle._run()
  |   File "C:\Users\10905\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
  |     self._context.run(self._callback, *self._args)
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
  |     return await coro
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\message.py", line 496, in check_and_run_matcher
  |     if not await _check_matcher(
  | > File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\message.py", line 400, in _check_matcher
  |     if not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 403, in check_rule
  |     return event_type == (cls.type or event_type) and await cls.rule(
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\internal\rule.py", line 97, in __call__
  |     with catch({SkippedException: _handle_skipped_exception}):
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\internal\rule.py", line 98, in __call__
  |     async with anyio.create_task_group() as tg:
  |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "E:\LLBOT\rainbowdashnb\.venv\Lib\site-packages\nonebot\internal\rule.py", line 95, in _run_checker
    |     result &= is_passed
    | TypeError: unsupported operand type(s) for &=: 'bool' and 'NoneType'
    +------------------------------------

**Comment by WhyPilotXia** [comment]
一样，返回内容：
12-05 21:00:01 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=nonebot-plugin-ncm, lineno=103).
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Administrator\Desktop\lhcbot-chongyun\bot.py", line 42, in <module>
  |     nonebot.run(app="__mp_main__:app")
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 337, in run
  |     get_driver().run(*args, **kwargs)
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
  |     uvicorn.run(
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 579, in run
  |     server.run()
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
  |     return asyncio.run(self.serve(sockets=sockets))
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
  |     return loop.run_until_complete(main)
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
  |     self.run_forever()
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
  |     super().run_forever()
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
  |     self._run_once()
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
  |     handle._run()
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
  |     self._context.run(self._callback, *self._args)
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
  |     return await coro
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 496, in check_and_run_matcher
  |     if not await _check_matcher(
  | > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 400, in _check_matcher
  |     if not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 403, in check_rule
  |     return event_type == (cls.type or event_type) and await cls.rule(
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\rule.py", line 97, in __call__
  |     with catch({SkippedException: _handle_skipped_exception}):
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\rule.py", line 98, in __call__
  |     async with anyio.create_task_group() as tg:
  |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\rule.py", line 95, in _run_checker
    |     result &= is_passed
    | TypeError: unsupported operand type(s) for &=: 'bool' and 'NoneType'
    +------------------------------------
