### ISSUE TITLE
无法获取上次登录ip

### ISSUE THREAD

**Issue by bridgeL** [kitUIN/nonebot-plugin-ncm#7]
```log
11-04 09:25:18 [ERROR] nonebot | Failed to import "nonebot-plugin-ncm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main 
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code       
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\bot.py", line 16, in <module>
    nonebot.load_plugin("nonebot-plugin-ncm")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot-plugin-ncm\__init__.py", line 17, in <module>
    from .data_source import nncm, music, ncm_config, playlist, setting, Q, cmd
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot-plugin-ncm\data_source.py", line 253, in <module>
    nncm.get_user_info()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot-plugin-ncm\data_source.py", line 101, in get_user_info
    f"欢迎您网易云用户:{GetCurrentSession().nickname} [{GetCurrentSession().uid}],上次登录IP:{GetCurrentSession().lastIP}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyncm\__init__.py", line 139, in lastIP
    self.login_info["content"]["profile"]["lastLoginIP"]
KeyError: 'lastLoginIP'
```
似乎是pyncm的问题

目前的解决方法是
```py
# nonebot-plugin-ncm\data_source.py line 98
    @staticmethod
    def get_user_info():
        logger.success(
            f"欢迎您网易云用户:{GetCurrentSession().nickname} [{GetCurrentSession().uid}]")
# 删除 上次登录IP:{GetCurrentSession().lastIP}
```

**Comment by kitUIN** [comment]
八天前就修了,结果发现自己忘记发布版本
