### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by chuanchuan744** [kitUIN/nonebot-plugin-ncm#9]
**系统 windows2019
登录账户后无法加载插件
报错**

12-10 02:00:50 [SUCCESS] nonebot-plugin-ncm | 欢迎您网易云用户:Bracelet_CN [1698161447]
12-10 02:00:50 [SUCCESS] nonebot | Succeeded to import "nonebot-plugin-ncm"
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\program files\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\program files\python\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 25, in <module>
    nonebot.load_plugin('nonebot-plugin-ncm')
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line 26, in load_plugin
    manager = PluginManager([module_path])
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", line 52, in __init__
    self.prepare_plugins()
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", line 99, in prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: nonebot-plugin-ncm! Check your plugin name

**Comment by kitUIN** [comment]
你这明显是重复载入插件了
解决办法如下:
删除`bot.py`中`nonebot.load_plugin('nonebot-plugin-ncm')`
或者删除`pyproject.toml`文件中`[tool.nonebot]` `plugin`项中的`nonebot-plugin-ncm`

**Comment by chuanchuan744** [comment]
感谢 已解决
